server:
  port: 5001

spring:
  jpa:
    #PostgresSQL settings
#    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
    #MySQL jps settings
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  # Postgres SQL settings
#  datasource:
#    url: jdbc:postgresql://localhost:5432/bankaccount
#    username: postgres
#    password: msqlAdmin1!
    # MySQL DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
    username: root
    password: msqlAdmin1!
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankaccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
